cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.yarn-cache

services:
  - mysql

sudo: true

language: php

php:
  - 7.0

matrix:
  fast_finish: true

env:
  - DB_USERNAME=root

before_install:
  - bash .travis.install-mysql-5.7.sh
  - nvm install 4.2
  - nvm use 4.2
  - ./bin/db_setup.sh
  - ./build.sh

script: ./vendor/bin/phpunit
