cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.yarn-cache

addons:
  mariadb: 10.0

language: php

php:
  - 7.0

matrix:
  fast_finish: true

env:
  - DB_USERNAME=root

before_install:
  - nvm install 4.2
  - nvm use 4.2
  - ./bin/db_setup.sh
  - ./build.sh

script: ./vendor/bin/phpunit
