cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.yarn-cache

sudo: true

language: php

php:
  - 7.1

matrix:
  fast_finish: true

env:
  global:
    - DB_USERNAME=root
    - SLACK_ENDPOINT=https://myconan.net/null/
    - PATH=$HOME/.yarn/bin:$PATH
    - APP_ENV=testing
    - SESSION_DRIVER=array
    - CACHE_DRIVER=array
    - CAMO_KEY=""
    - ES_VERSION=1.7.6 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.zip

install:
  - sudo ./bin/mysql_debian_install
  - nvm install 6.11
  - nvm use 6.11
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - ./bin/db_setup.sh
  - ./build.sh

  # elasticsearch setup
  - wget "${ES_DOWNLOAD_URL}"
  - unzip "elasticsearch-${ES_VERSION}.zip"
  - ./"elasticsearch-${ES_VERSION}/bin/elasticsearch" &
  - sleep 10 # wait until the server is up
  - php artisan es:index-users --yes
  - php artisan es:index-documents --yes

script: ./bin/phpunit
