cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - vendor
  yarn: true

os: linux
dist: focal

language: php

php:
  - 7.4

services:
  - redis
  - mysql

env:
  global:
    - APP_ENV=testing
    - APP_KEY=base64:q7U5qyAkedR1F6UhN0SQlUxBpAMDyfHy3NNFkqmiMqA=
    - APP_URL=http://127.0.0.1:8000
    - CACHE_DRIVER=redis
    - CACHE_DRIVER_LOCAL=array
    - DB_USERNAME=root
    - ES_VERSION=6.8.12 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.zip
    - GITHUB_TOKEN=98cbc568911ef1e060a3a31623f2c80c1786d5ff
    - NOTIFICATION_ENDPOINT=ws://127.0.0.1:3000
    - NOTIFICATION_SERVER_LISTEN_PORT=3000
    - OSU_INSTALL_DEV=1
    - PAYMENT_SANDBOX=true
    - SESSION_DRIVER=redis
    - SHOPIFY_DOMAIN=notarealdomainortld
    - SHOPIFY_STOREFRONT_TOKEN=notreal
    - SLACK_ENDPOINT=https://myconan.net/null/

# lint job doesn't need most of the setup except node update so they're separated out here from install
before_install:
  - travis_retry nvm install 12
  - nvm use 12

install:
  # elasticsearch setup (part 1)
  - travis_retry bash -c 'wget "${ES_DOWNLOAD_URL}"'
  - unzip "elasticsearch-${ES_VERSION}.zip"
  - ./"elasticsearch-${ES_VERSION}/bin/elasticsearch" > elasticsearch.log &

  - phpenv config-add travis-php.ini
  - ./bin/db_setup.sh
  - ./build.sh

  # elasticsearch setup (part 2)
  # wait until es server is up
  - wget -q --waitretry=10 --retry-connrefused -T 60 -O - http://127.0.0.1:9200
  - php artisan es:create-search-blacklist
  - php artisan es:index-documents --yes
  - php artisan es:index-wiki --create-only --yes

jobs:
  fast_finish: true
  include:
    - name: phpunit
      env:
        - APP_URL=http://localhost
      script: ./bin/phpunit.sh

    - name: browser tests
      addons:
        chrome: stable
        <<: *addons
      script: ./bin/run_dusk.sh

    - name: lint
      env:
        - OSU_SKIP_ASSET_BUILD=1
      addons:
      install:
      services:
      script:
        - yarn
        - yarn lint
        - ./bin/update_licence.sh -nf

    - name: karma
      env:
        - OSU_SKIP_ASSET_BUILD=1
      script:
        - yarn
        - yarn karma start --single-run --browsers ChromeHeadless

    - name: apidoc
      env:
        - OSU_SKIP_ASSET_BUILD=1
      script:
        - php artisan apidoc:generate

after_script:
  - test -f elasticsearch.log && cat elasticsearch.log
  - test -f osu-notification-server/server.log && cat osu-notification-server/server.log
