cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - vendor
  yarn: true

dist: xenial
sudo: false

language: php

php:
  - 7.2

matrix:
  fast_finish: true

services:
  - mysql
  - redis

addons:
  chrome: stable

env:
  global:
    - APP_ENV=testing
    - APP_KEY=base64:q7U5qyAkedR1F6UhN0SQlUxBpAMDyfHy3NNFkqmiMqA=
    - APP_URL=http://127.0.0.1:8000
    - CACHE_DRIVER=redis
    - DB_USERNAME=root
    - ES_VERSION=6.6.0 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.zip
    - GITHUB_TOKEN=98cbc568911ef1e060a3a31623f2c80c1786d5ff
    - OSU_INSTALL_DEV=1
    - PAYMENT_SANDBOX=true
    - SESSION_DRIVER=redis
    - SHOPIFY_DOMAIN=notarealdomainortld
    - SHOPIFY_STOREFRONT_TOKEN=notreal
    - SLACK_ENDPOINT=https://myconan.net/null/

install:
  # elasticsearch setup (part 1)
  - travis_retry bash -c 'wget "${ES_DOWNLOAD_URL}"'
  - unzip "elasticsearch-${ES_VERSION}.zip"
  - ./"elasticsearch-${ES_VERSION}/bin/elasticsearch" > elasticsearch.log &

  - travis_retry nvm install 10
  - nvm use 10
  - phpenv config-add travis-php.ini
  - ./bin/db_setup.sh
  - ./build.sh

  # elasticsearch setup (part 2)
  # wait until es server is up
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - php artisan es:index-documents --yes

jobs:
  include:
    - script: ./bin/phpunit
      name: "phpunit"
    - script: ./bin/run_dusk.sh
      name: "browser tests"

after_script:
  - cat elasticsearch.log
